config/routes.rb
Rails.application.routes.draw do
  # get 'dashboard/all_bookings'
  # get 'dashboard/all_flats'

  devise_for :users

  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [ :edit, :update ]
  # resources :bookings, only: [:index ]

  resources :flats do
    resources :bookings, only: [ :create ] do
    # accept or decline in bookings controller
      member do
        patch 'accept', to: "bookings#accept"
        patch 'decline', to: "bookings#decline"
      end
    end
  end
  # dashboard/bookings or dashboard/flats ..all_bookings for path in navbar "My Bookings"
  get '/dashboard/bookings', to: 'dashboard#all_bookings', as: 'all_bookings'
  get '/dashboard/flats', to: 'dashboard#all_flats', as: 'all_flats'
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

  # all my bookings made -> others flats
  def all_bookings
    @my_bookings = current_user.bookings.order(checkin: :asc)
    authorize :dashboard, :all_bookings?
  end

  # all flats booked by others
  def all_flats
    @my_flats = current_user.flats
    authorize :dashboard, :all_flats?

    # all bookings -> ordered by check-in date FIFO
    @bookings = policy_scope(Booking).order(checkin: :asc).all

    # bookings related to my own flats
    @bookings_of_flat = []
      # all flats -> others as well || or @my_flats.bookings...
      @my_flats.each do |flat|
        @bookings.each do |booking|
          # check once more booked flat has id as my flat
          if booking.flat_id == flat.id
            # display every booking - from new to old
            @bookings_of_flat << booking
          end
        end
    end
    # needs to be here to after loop -> to include all, not just 1
      return @bookings_of_flat
  end
end


# 1. show all my flats - created
# 2. show all my bookings - others owners
# e.x. User.order('id ASC').reorder('name DESC')

app/views/dashboard/all_bookings.html.erb
<div class="container">
  <h1>All my bookings</h1>

    <% @my_bookings.each do |booking| %>
        <div class="row">
          <div class="col-xs-12 col-md-6">
            <ul>
              <li>Booked by: <%= booking.user.email %></li>
              <% if booking.status == 'accepted' %>
              <li>Status: <strong style="color: green;"><%= booking.status %></strong></li>
              <% else %>
              <li>Status: <strong style="color: red;"><%= booking.status %></strong></li>
              <% end %>
              <li>Booked at: <%= booking.created_at %></li>
              <li>Flat-id: <%= booking.flat.name %></li>
              <li>Flat-id: <%= booking.flat.location %></li>
              <strong><li>Owner: <%= booking.flat.user.email %></li></strong>
              <li>Check-in: <%= booking.checkin %></li>
              <li>Check-out: <%= booking.checkout%></li>
           </ul>
          </div>

      <div class="cards padded">
          <div class="col-xs-12 col-md-6">
            <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)),
              url('<%= booking.flat.photo %>')">
              <%= link_to "", flat_path(booking.flat), class: 'card-link' %>
            </div>
            <%#= link_to flat_booking_path(booking.flat, booking) do ....%>
          </div>
        </div>

      </div>
      <hr>
    <% end %>

</div>

  <!-- add_foreign_key "bookings", "flats" booking.flat -->
  <!-- add_foreign_key "bookings", "users" => booking.user -->
  <!-- Flat-id:#<Flat:0x00007fe15376dce8> -->

app/views/dashboard/all_flats.html.erb
<div class="container">

<!-- 1. all my flats -> to edit, delete - if not booked ==>> see in separate profile -->
<!-- 1b. get detail info -> when click on it ==> flat show page... edit etc. -->
<!-- 2. all booked flats -> change status, see who booked, when, checkin/out -->
  <h2>All my flats - #<%= @my_flats.count %></h2>

  <p class="text-center"> ALL bookings - including mine: <strong><%= @bookings.count %></strong> | bookings of my flats: <strong><%= @bookings_of_flat.count %></strong></p>

  <div class="row">
    <% @my_flats.each do |flat| %>
      <div class="col-xs-12 col-md-3">
        <!-- <li>My flat email: <%#= flat.user.email %></li> -->
        <!-- <li>My user id: <%#= flat.user.id %></li> -->
      <!-- display all FLATS on its CARD (even not booked) -> 1 row (above loop) -->
          <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)),
            url('<%= flat.photo %>')">
            <!-- change link for iterating through bookings_of_flat (flat_path(others.flat)-->
            <%= link_to "", flat_path(flat), class: 'card-link' %>
          </div>
        </div>
    <% end %>
  </div>
  <!-- end of my_flats loop -->

  <hr>

  <!-- INFO ABOUT BOOKED FLATS (repeated booking of 1 flat, or not all flats displayed) -->
  <!-- all booking details - flat ordered by check-in date FIFO -->
  <h3 class="text-center">Management of all my booked flats</h3>
  <hr>

  <% @bookings_of_flat.each do |booked| %>
    <div class="row">
      <div class="col-xs-12 col-md-5 col-md-offset-1">
        <img src="<%= booked.flat.photo%>" height=200 width=250>

        <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)),
          url('<%= booked.flat.photo %>')">
          <%= link_to "", flat_path(booked.flat), class: 'card-link' %>
        </div>
      </div>

      <div class="col-xs-12 col-md-6">
        <li>Booked by: <%= booked.user.email%></li>
        <li>Flat id: <%= booked.flat_id %></li>
        <li>Booking status: <strong><%= booked.status %></strong>
          <%= link_to 'Accept', accept_flat_booking_path(booked.flat, booked),
          method: :patch,
          class: " btn btn-success" %>
          <%= link_to 'Decline', decline_flat_booking_path(booked.flat, booked),
          method: :patch,
          class: " btn btn-danger" %>
        </li>
        <li>Date: <%= booked.checkin %> : <%= booked.checkin %></li>
        <li><strong><%= booked.flat.address %></strong></li>
        <li><strong><%= booked.flat.location %></strong></li>
        <li><strong><%= booked.flat.price %>£</strong></li>

        <!-- as default link_to is https GET request -> change to path -->
        <!-- accept_flat_booking PATCH  /flats/:flat_id/bookings/:id/accept(.:format)      bookings#accept
        decline_flat_booking -->
      </div>
    </div>
    <!-- every row is repeated -->
    <hr>
  <% end %>

</div>

<!-- GET INFO ABOUT ALL BOOKINGS TO PARTICULAR FLAT -> can have more bookings to 1 flat -->
<%# flat.bookings.each do |bookin| %>
  <!-- <img src="<%#= bookin.flat.photo%>" height=100 width=100> -->
  <%#= bookin.flat_id %>
  <!-- <p> who booked<%#= bookin.user.email %></p> -->
<%# end %>