config/routes.rb
Rails.application.routes.draw do
  # get 'dashboard/all_bookings'
  # get 'dashboard/all_flats'

  devise_for :users

  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [ :edit, :update ]
  # resources :bookings, only: [:index ]

  resources :flats do
    resources :bookings, only: [ :create ] do
    # accept or decline in bookings controller
      member do
        patch 'accept', to: "bookings#accept"
        patch 'decline', to: "bookings#decline"
      end
    end
  end
  # dashboard/bookings or dashboard/flats ..all_bookings for path in navbar "My Bookings"
  get '/dashboard/bookings', to: 'dashboard#all_bookings', as: 'all_bookings'
  get '/dashboard/flats', to: 'dashboard#all_flats', as: 'all_flats'
end

app/models/flat.rb
class Flat < ApplicationRecord
  belongs_to :user

  has_many :bookings, dependent: :destroy

  mount_uploader :photo, PhotoUploader

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  validates :name, :description, :photo, :price, :address, :location, :capacity, presence: true
  validates :capacity, inclusion: { in: 1..8 }
  # validates :name, :description, :price, :address, :location, :capacity, presence: true

  include PgSearch
  pg_search_scope :search_by_columns,
    against: [ :name, :description, :address, :location ],
    using: {
      tsearch: { prefix: true } # <-- now `awesome fl` will return something!
    }
end


# 1. rails g model Flat name:string description:text photo:string price:integer address:string location:string capacity:integer  user:references
# 2. has many bookings -> when destroy flat -> bookings as well
# 3. added carrierwave gem for photo - app/uploaders/photo_uploader.rb, form update for flat
# 4. added line for using map with lat, lng for address
# 5. include PgSearch gem -> define what to search -> all columns rails c: Flat.search_by_columns("central fla")
# !!! needs to uncomment  photo_uploader -> otherwise error not seed complete
# then display photo_uploader for local not run error for html file

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  before_action :set_flat, only: [:show, :edit, :update, :destroy]

  def index
    # will change by pundit
    # @flats = Flat.all
    # @flats = policy_scope(Flat).order(created_at: :desc)

    if params[:query].present?
      # authorize all
      @flats = policy_scope(Flat).order(created_at: :desc)
      # define model method for pg_search
      @flats = Flat.search_by_columns(params[:query])
      # showing map with markers

      # HANDLE IF FLAT FOUND BUT IS MINE -> not displayed on map nor the card in view
      @markers = @flats.where.not(user: current_user).map do |flat|
        {
          lat: flat.latitude,
          lng: flat.longitude,
          infoWindow: { content: render_to_string(partial: "/flats/map_box", locals: { flat: flat }) }
          # Uncomment the above line if you want each of your markers to display a info window when clicked
          # (you will also need to create the partial "/flats/map_box")
        }
      end
    else
      @flats = policy_scope(Flat).order(created_at: :desc)

      # displaying just flats which are not mine
      @flats = Flat.where.not(latitude: nil, longitude: nil, user: current_user)

      @markers = @flats.map do |flat|
        {
          lat: flat.latitude,
          lng: flat.longitude,
          infoWindow: { content: render_to_string(partial: "/flats/map_box", locals: { flat: flat }) }
          # Uncomment the above line if you want each of your markers to display a info window when clicked
          # (you will also need to create the partial "/flats/map_box")
        }
      end
    end
  end

  # render form
  def new
    @flat = Flat.new
    authorize @flat
  end

  def create
    @flat = Flat.new(flat_params)
    # assign signed-in user
    @flat.user = current_user
    authorize @flat

    if @flat.save
      redirect_to flat_path(@flat)
    else
      render :new
    end
  end

  def show
    # authorization in set_flat
    # added booking form as partial to flat
    @booking = Booking.new
  end

  def edit
    # authorize @flat
  end

  def update
    # authorize @flat
    # allowed params; redirect to concrete flat
    if @flat.update(flat_params)
      redirect_to @flat
    else
      render :edit
    end
  end

  # def destroy
  # end

  private

  def set_flat
    @flat = Flat.find(params[:id])
    authorize @flat
  end

  def flat_params
    params.require(:flat).permit(:name, :description, :photo, :price, :address, :location, :capacity, :latitude, :longitude)
  end
end

app/views/flats/_map_box.html.erb
<div>
 <div class="infowindow-card">
  <div class="infowindow-title"><%= flat.name %></div>
    <%#= cl_image_tag flat.photo, height: 130, width: 130, crop: :fill %>
    <% if policy(flat).show? %>
      <%= link_to '', flat_path(flat), class: 'infowindow-link' %>
        <div class="infowindow-img" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= cl_image_path flat.photo, height: 150, width: 150, crop: :fill  %>')">
        </div>
    <% end %>
  </div>
  <%#=link_to "Find more about this flat", flat_path(flat)%>
</div>

<!-- 1. cl_image_path vs. cl_image_tag (url x img tag) -->

app/views/flats/_simple_form.html.erb
<div class="container">
  <% if @flat.name.nil? %>
    <h3>Add a new flat</h3>
  <% else %>
    <h3>Update your <%= @flat.name %></h3>
  <% end %>
    <%= simple_form_for [@flat] do |f| %>
        <%= f.input :name, input_html: {class: "input-from-new"} %>
        <%= f.input :description, input_html: {class: "input-from-new"} %>
        <%#= f.input :photo, input_html: {class: "input-from-new"} %>
        <%= f.input :photo, input_html: {class: "input-from-new"} %>
        <%= f.input :photo_cache, as: :hidden %>
        <%= f.input :price, input_html: {class: "input-from-new"} %>
        <%= f.input :address, input_html: {class: "input-from-new", id: "flat_address"} %>
        <%= f.input :location, input_html: {class: "input-from-new"} %>
        <%= f.input :capacity, collection: 1..8, default: 1, input_html: {class: "input-from-new"} %>
        <%= f.submit "Upload flat", class: "btn btn-primary" %>
    <% end %>
    <br>
    <i class="fas fa-redo"></i> <%= link_to "Back to flats", root_path, class: ''%>
    <br>
</div>


<!-- - flat_address important for autocomplete.js in components - js -->

app/views/flats/edit.html.erb
<%= render 'simple_form' %>

<hr>

<i class="fas fa-redo"></i> <%= link_to "Back to flats", root_path, class: '' %>

app/views/flats/index.html.erb
  <!-- array of markers as a data attribute of our map div: -->
  <div
    id="map"
    style="width: 100%;
    height: 400px;"
    data-markers="<%= @markers.to_json %>">
  </div>

<div class="container">
  <!-- if searching flats not in DB, NOT use nil OR my flats not showing in map nor cards -->
  <%  if params[:query].present? && @flats.count == 0 || params[:query].present? && @markers.count == 0 %>
      <div class="text-center">
        <h2>No flats for this search ...</h2>
        <br>
        <h2><%= link_to "All Flats", flats_path %></h2>
      </div>
  <% else %>

  <!-- HAVE 1 ROW => ALL CARDS INSIDE -->
  <div class="row">
    <!-- displayed cards -->
    <div class="cards padded">
      <% @flats.each do |flat| %>
        <!-- DISPLAY JUST OTHERS FLATS -> NOT YOUR OWN -->
        <% unless current_user == flat.user %>
          <div class="col-xs-12 col-sm-6 col-md-4">
            <!-- <h2 class="card-title text-center">Our beloved drinks</h2> -->
            <% if flat.photo? %>
              <!-- USING FIT PICTURE -> IS NOT ZOOMED IN SO MUCH like fill -->
              <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= flat.photo %>')">
                <div class="card-category"><%= flat.name %></div>
                <div class="card-description"></div>
                <!-- <a class="card-link" href="#" ></a> -->
                <% if policy(flat).show? %>
                  <%#= link_to 'Destroy', restaurant, method: :delete, data: { confirm: 'Are you sure?' } %>
                  <%= link_to '', flat_path(flat), class: 'card-link' %>
                <% end %>
              </div>
              <!-- url('https://www.book-a-flat.com/images/paris-salon-3.jpg');"> -->
              <!-- url('< cl_image_path (flat.photo), height: 500, width: 600, crop: :fit %>');"> -->
              <!-- url('https://source.unsplash.com/500x400/?cocktail');"> -->
            <% else %>
              <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= image_path("logo.png") %>');">
                <div class="card-category"><%= flat.name %></div>
                <div class="card-description"></div>
                <!-- <a class="card-link" href="#" ></a> -->
                <%= link_to "", flat_path(flat), class: 'card-link' %>
              </div> <!-- end of card -->
            <% end %>
          </div>
        <% end %> <!-- END needs to be above div for columns -->
      <% end %>
    </div> <!-- cards padded -->
  </div> <!-- row -->
  <% end %>
</div>

  <!-- data-markers="<%#= @markers.to_json %>" -->

app/views/flats/new.html.erb
<%= render 'simple_form' %>

app/views/flats/show.html.erb
<div class="container">
  <h1>Detailed flat</h1>
  <%= @flat.name %>
  <%= @flat.description %>
  <%= @flat.price %>
  <%= @flat.address %>
  <%= @flat.location %>
  <hr>
  <%= @flat.user.email %>
  <br>

<div class="row">
  <div class="col-xs-12 col-md-6">
    <%= image_path @flat.photo  %>

    <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= cl_image_path @flat.photo, height: 500, width: 600, crop: :fit %>')">
    </div>
    <%= link_to 'Back to flats', flats_path, class: "btn btn-danger" %>
  </div>

  <div class="col-xs-12 col-md-6">
    <!-- check if current user is NOT owner -->
    <% unless current_user == @flat.user %>
      <!-- added booking form -->
      <%= render 'bookings/new' %>
      <%#= link_to 'Book flat',  new_flat_booking_path(@flat), class: "btn btn-primary" %>
      <% else %>
        <% if policy(@flat).update? %>
          <%= link_to "Update flat", edit_flat_path(@flat) %>
        <% end %>
    <% end %>
  </div>

</div>

  <%#= link_to "Delete", flat_path(@flat), class: "btn", method: :delete, data: { confirm: "Are you sure?" } %>




<!-- 1. in index -> show just others flats - not my own to book -->
<!-- 2. I am redirect when click => My property to detail flat -> where I could edit/delete/accept? -->
<!-- for displaing image <%#= cl_image_tag @article.photo, height: 300, width: 400, crop: :fill %> -->
<!-- url for http address from net -  url('<%= image_path @flat.photo %>');"> -->