config/routes.rb
Rails.application.routes.draw do
  # get 'dashboard/all_bookings'
  # get 'dashboard/all_flats'

  devise_for :users

  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [ :edit, :update ]
  # resources :bookings, only: [:index ]

  resources :flats do
    resources :bookings, only: [ :create ] do
    # accept or decline in bookings controller
      member do
        patch 'accept', to: "bookings#accept"
        patch 'decline', to: "bookings#decline"
      end
    end
  end
  # dashboard/bookings or dashboard/flats ..all_bookings for path in navbar "My Bookings"
  get '/dashboard/bookings', to: 'dashboard#all_bookings', as: 'all_bookings'
  get '/dashboard/flats', to: 'dashboard#all_flats', as: 'all_flats'
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.png" %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

      <!-- Links when logged in -->
      <%= link_to "All Flats", flats_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "My Bookings", all_bookings_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "My Property", all_flats_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%#= link_to "Messages", "#", class: "navbar-wagon-item navbar-wagon-link" %>

      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag "http://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
                <%= current_user.email %>
              <% end %>
            </li>
            <li>
              <% if policy(Flat).create? %>
                <%= link_to new_flat_path do %>
                  <i class="fa fa-plus"></i>  <%= t(".add_flat", default: "Add Flat") %>
                  <% end %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on MOBILE -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" id="hamburger-color" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <% if user_signed_in? %>

          <!-- Links when logged in -->
          <li><%= link_to "All Flats", flats_path, class: "" %></li>
          <li><%= link_to "My Bookings", all_bookings_path, class: "" %></li>
          <li><%= link_to "My Property", all_flats_path, class: "" %></li>

          <% if policy(Flat).create? %>
            <li><%= link_to new_flat_path, class: "" do %>
              <i class="fa fa-plus"></i>  <%= t(".add_flat", default: "Add Flat") %> </li>
              <% end %>
          <% end %>
          </li>
          <li>
            <%= link_to destroy_user_session_path, method: :delete do %>
              <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
            <% end %>
          </li>
        <!-- <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li> -->
        <% else %>
          <!-- Login link (when logged out) -->
          <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
        <% end %>
      </ul>
    </div>
  </div>
</div>